### ISSUE TITLE
Support for backwards numbering

### ISSUE THREAD

**Issue by sylae** [katycat5e/NumberManager#5]
I've been working on a skin for the DH4, and in skinning the right-hand door with numbers, I had an issue wherein the numbers would render backwards (ie train number 1234 appears ingame as 4321). I *think* this is due to the texture being 90 degrees clockwise from "up".

I was able to get around this by setting Kerning to 2*CharWidth, but this is kinda jank and obvs wont work for variable-pitch glyphs. It'd be handy if there was a way to set an attribute to render "right to left" in these cases, or some other solution.

xml and numbers i'm using to replicate:
```xml
<NumberConfig TargetTexture="LocoDH4_ExteriorBody_01d" BlendMode="Normal" MinNumber="0" MaxNumber="9999" Offset="0">
    <Fonts>
        <NumberFont Height="45"
                    CharX=    " 15, 51, 87,123,159,195,231,267,303,339"
                    CharY=    " 45, 45, 45, 45, 45, 45, 45, 45, 45, 45"
                    CharWidth=" 36, 36, 36, 36, 36, 36, 36, 36, 36, 36"/>
                    <!--         0,  1,  2,  3,  4,  5,  6,  7,  8,  9-->

         <!-- add Kerning="-72" to fix -->
        <NumberFont Height="45" Orientation="Vertical"
                    CharX=    " 15, 15, 15, 15, 15, 15, 15, 15, 15, 15"
                    CharY=    " 81,117,153,189,225,261,297,333,371,405"
                    CharWidth=" 36, 36, 36, 36, 36, 36, 36, 36, 36, 36"/>
                    <!--         0,  1,  2,  3,  4,  5,  6,  7,  8,  9-->
    </Fonts>
    
    <AttachPoints>
        <NumAttachPoint FontIdx="0" X="822" Y="1072"/>
        <NumAttachPoint FontIdx="1" X="1706" Y="918"/>
    </AttachPoints>
</NumberConfig>
```
![num](https://github.com/katycat5e/NumberManager/assets/2791628/9804c836-e71d-421e-86d0-2751f04d9969)

**Comment by katycat5e** [comment]
This feature exists, you can set ReverseDigits="true" on the font.

**Comment by sylae** [comment]
Oh cool! sorry for the bother :)

Would it be possible to get that added to the wiki/documentation for the next person? I don't see it listen on there

**Comment by katycat5e** [comment]
Added to docs
